# Generated by Django 4.2 on 2026-05-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('VERIFIED', 'Verified'), ('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20),
        ),
    ]
